### PR TITLE
Fix sourceAFRICA group label

### LINKED ISSUE #431: Allow Multiple Groups for sourceAfrica documents
Allow creation of multiple sourceAfrica groups for use in different sections of the CMS

### PR DESCRIPTION
**Pull request by kelvinkipruto**
## Description

This PR fixes the sourceAFRICA label to [clarify](https://dc.sourceafrica.net/help/searching) that what we need is organisation short name i.e. group `id` and not `name`.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Screenshots

N/A

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

### CODE REVIEW

**Comment by kilemensi** [comment]
Can you may be describe the approach @kelvinkipruto?

**Comment by kelvinkipruto** [comment]
@kilemensi Updated.

**Comment by kilemensi** [comment]
Thanks @kelvinkipruto but I'm still not sure why we need a collection though.

My understanding is the only thing needed for sourceAFRICA integration is just the organisation/group id. Why not just type it in the block? What does having a separate collection & extra relationship add to the mix?

**Comment by kelvinkipruto** [comment]
Ahaa, So simple. Thanks.

File: apps/charterafrica/src/payload/blocks/EmbeddedDocuments.js [hunk 1]
```diff
@@ -46,14 +46,13 @@ const EmbeddedDocuments = {
       type: "group",
       fields: [
         {
-          name: "group",
+          name: "groupId",
```
Comment (kilemensi) [inline apps/charterafrica/src/payload/blocks/EmbeddedDocuments.js:49]: What about the current code that's using group? Deploying this code as is would break that functionality.

**Review by kilemensi — APPROVED** [review]
🚀
