### PR TITLE
Built-time Image src Resolution

### LINKED ISSUE #1068: Built-time Image `src` Resolution
**Description**

Images on custom error pages (e.g., 404.tsx, 500.tsx) are not loading in production because Next.js encodes image URLs with localhost:3000 at build time. This results in broken images when deployed to a different environment.

**Steps to Reproduce**

1. Navigate to non existent page on [Charter Africa](https://charter.africa/sd) or [Code for Africa](https://cfa.dev.codeforafrica.org/c).
2. Inspect the image source in DevTools; it appears as `http://localhost:3000/media/cfa-logo.svg` instead of `/media/cfa-logo.svg`

**Expected Behavior**
Image URLs should remain relative (e.g., /images/error.png) so they work across different environments.
**Actual Behavior**
Image URLs are hardcoded with localhost:3000, causing them to break outside of a local environment.

### PR DESCRIPTION
**Pull request by koechkevin**
## Description

Images on custom error pages (e.g., 404.tsx, 500.tsx) are not loading in production because Next.js encodes image URLs with localhost:3000 at build time. This results in broken images when deployed to a different environment.

Fixes #1068

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

File: apps/charterafrica/src/payload/collections/Media.js [hunk 1]
```diff
@@ -24,6 +24,12 @@ const Media = {
       ({ doc }) => ({
         ...doc,
         alt: doc.alt ?? null,
+        /*
+        Since we are setting ENV PAYLOAD_PUBLIC_APP_URL=http://localhost:3000 at build time, generating static pages(404,500) ends up with image urls with `http://localhost:3000/media/cfalogobw.svg`.
+        In this proposal, we are just returning pathnames without hostname since our next js apps and payload are served from the same instance.
+        */
+        src: new URL(doc.url).pathname,
+        url: new URL(doc.url).pathname,
       }),
```
Comment (kilemensi) [inline apps/charterafrica/src/payload/collections/Media.js:33]: No need for two `new URL` calls; just create a proper function with `return`.
```suggestion
      ({ doc }) => {
        // Can't use absolute URLs in src because we set PAYLOAD_PUBLIC_APP_URL to localhost at build-time & will lead to 404 at runtime
        // Solution: use relative URLs
        const { pathname } = new URL(doc.url);
        return {
          ...doc,
          alt: doc.alt ?? null,
          src: pathname,
          url: pathname,
        }
      },
```

PS: This could even move to somewhere reusable since I assume it's something we're going to apply to all apps?

File: docker-compose.yml [hunk 2]
```diff
@@ -11,6 +11,7 @@ services:
         - SENTRY_ENVIRONMENT
         - SENTRY_ORG
         - SENTRY_PROJECT
+        - PAYLOAD_PUBLIC_APP_URL
```
Comment (kilemensi) [inline docker-compose.yml:14]: `docker-compose` is local dev only & I don't think we use 2 separate domain when doing local development

**Review by kilemensi — APPROVED** [review]
🚀 

--

Haven't tried it locally but the solution looks simple and clear to me!

File: apps/charterafrica/src/payload/collections/Media.js (hunk 1 above)
Comment (koechkevin) [reply apps/charterafrica/src/payload/collections/Media.js]: > PS: This could even move to somewhere reusable since I assume it's something we're going to apply to all apps?
@kilemensi 
We can't somehow move this to packages, it tries to resolve other files with jsx syntax when you import in payload related files.
image

**Review by m453h — APPROVED** [review]
LGTM  🚀

File: packages/commons-ui-core/src/utils/transformDocMediaUrl.js [hunk 3]
```diff
@@ -0,0 +1,13 @@
+const transformDocMediaUrl = (doc) => {
```
Comment (kilemensi) [inline packages/commons-ui-core/src/utils/transformDocMediaUrl.js:1]: `payload`-related functionality should **not** be in `@commons-ui/core` or `@commons-ui/next` packages @koechkevin .

**Comment by kilemensi** [comment]
If this works @koechkevin, then lets merge it as is. Create an issue (if it doesn't exist) to consolidate all payload-related functionality into one package that will be tackled in a different PR.
