### PR TITLE
@/CivicSignal: Fix previews on research blog content

### LINKED ISSUE #907: Fix CivicSignal preview issues on ResearchBlog

### LINKED ISSUE #999: Previews not working when draft mode is enable on the CivicSignal Research blog
Currently previews are not working when draft mode is enabled in the CivicSignal Research blog.

### PR DESCRIPTION
**Pull request by m453h**
## Description
This PR introduces several fixes to the CivicSignal Research blog to enable previews and address some issues on the blog's UI.

Fixes #999 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

File: apps/civicsignalblog/src/components/ArticleGrid/ArticleGrid.js [hunk 1]
```diff
@@ -26,12 +26,12 @@ const ArticleGrid = React.forwardRef(function ArticleGrid(props, ref) {
   return (
     <Section sx={{ px: { xs: "20px", sm: 0 }, ...sx }} {...other} ref={ref}>
       <Grid container sx={{ py: { xs: "28px", md: 8, lg: "105.29px" } }}>
-        <Grid
+        <Box
           item
           xs={12}
```
Comment (kilemensi) [inline apps/civicsignalblog/src/components/ArticleGrid/ArticleGrid.js:31]: Box doesn't support `item` or `xs` props.

File: apps/civicsignalblog/src/payload/access/canAccessApplication.js [hunk 2]
```diff
@@ -4,7 +4,7 @@ export default async function canAccessApplication(req, searchString) {
   if (user) {
     const app = headers["CS-App"] || user.currentApp || user.defaultApp;
     return (
-      app.toLowerCase() === searchString.toLowerCase() &&
+      app?.toLowerCase() === searchString.toLowerCase() &&
```
Comment (kilemensi) [inline apps/civicsignalblog/src/payload/access/canAccessApplication.js:7]: In what scenario will all of `headers["CS-App"]`, `user.currentApp`, and `user.defaultAp` be `undefined`?

File: apps/civicsignalblog/src/payload/components/allowedAppSelect/index.tsx [hunk 3]
```diff
@@ -32,7 +32,7 @@ function CustomSelectComponent({ path, label }) {
         path={path}
         name={path}
         options={options}
-        value={String(value)}
+        value={value ? String(value) : ``}
```
Comment (kilemensi) [inline apps/civicsignalblog/src/payload/components/allowedAppSelect/index.tsx:35]: Why do we need `String(value)` instead of just `value`?

**Review by kilemensi — APPROVED** [review]
LGTM!

File: apps/civicsignalblog/src/payload/access/canAccessApplication.js (hunk 2 above)
Comment (m453h) [reply apps/civicsignalblog/src/payload/access/canAccessApplication.js:7]: This only occurs when we login  on the admin UI after we have created the first account on a fresh install.
Because at the time of the account creation we can not render the  options for `user.CurrentApp` or user.defaultApp since these depend on the user's `allowedApps` which will always be undefined.

Comment (kilemensi) [reply apps/civicsignalblog/src/payload/access/canAccessApplication.js:7]: ... what do we do in that case? Is the user allowed to access any app?

Comment (m453h) [reply apps/civicsignalblog/src/payload/access/canAccessApplication.js:7]: If the user had selected Research app among their `allowedApps`, then we would default `user.CurrentApp `to `Research`, otherwise we would just allow them to manage collections that are not tied to any specific application i.e. Media and Users as  👇 

Screenshot 2024-11-14 at 13 21 50

File: apps/civicsignalblog/src/payload/components/allowedAppSelect/index.tsx (hunk 3 above)
Comment (m453h) [reply apps/civicsignalblog/src/payload/components/allowedAppSelect/index.tsx]: It was more of trying to overcome Typescript not knowing if value is really a string but I have added proper typing on the useField hook

**Review by kilemensi — APPROVED** [review]
