### PR TITLE
ClimateMapped Fixes

### LINKED ISSUE #974: How it Works Mobile View
The mobile view doesn't match the appearance in PesaYetu

### PesaYetu
Image

### ClimateMapped Africa
Image

### PR DESCRIPTION
**Pull request by kelvinkipruto**
## Description

This PR fixes a few bugs on ClimateMappedAfrica:
1. Searching for locations now works
2. How it works Moblie view #974
3. Navigation between regions not working #966 

Fixes #974 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Screenshots
image
image

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by kilemensi — COMMENTED** [review]
I'll let others do a deeper review but aren't we calling `fetchProfile` too many times? In `getNavBar`, `blockify`, etc.

If it's HURUmap profile page, profile should be loaded just once (in the `lib/data/common.js`?) and passed to all relevant functions/blocks.

File: apps/climatemappedafrica/src/components/HowItWorks/index.js [hunk 1]
```diff
@@ -148,16 +156,21 @@ function HowItWorks({
...
+            justifyContent={{
+              xs: "center",
+              md: "flex-end",
             }}
+            sx={(theme) => ({
+              marginBottom: {
+                xs: theme.typography.pxToRem(23),
+                md: 0,
+              },
+            })}
```
Comment (kilemensi) [inline apps/climatemappedafrica/src/components/HowItWorks/index.js:173]: Style the Box inside the Grid.

File: apps/climatemappedafrica/src/components/Navigation/ExploreNavigation/index.js [hunk 2]
```diff
@@ -72,8 +72,9 @@ function ExploreNavigation({ explorePagePath, logo, variant }) {
             <DropdownSearch
               icon={SearchIcon}
               href={explorePagePath}
-              placeholder="Search for a Location" // TODO: Read from cms
+              placeholder="Search for a Location"
```
Comment (kilemensi) [inline apps/climatemappedafrica/src/components/Navigation/ExploreNavigation/index.js:75]: Shouldn't this come from the CMS?

File: apps/climatemappedafrica/src/lib/data/blockify/index.js [hunk 3]
```diff
@@ -12,13 +12,19 @@ const propsifyBlockBySlug = {
   tutorial,
 };
 
-export const blockify = async (blocks, api, context, hurumap) => {
+export const blockify = async (
+  blocks,
+  api,
+  context,
+  hurumap,
+  hurumapProfile,
```
Comment (kilemensi) [inline apps/climatemappedafrica/src/lib/data/blockify/index.js:20]: Discuss with the team but I think the signature should be something like:
```js
blockify(page, api, context, settings) {
```

1. from `page`, we get `{ blocks }`,
2. `api` and `context` we all know already,
3. `settings` woulbe be `{ site, hurumap, <any other future setting> }`, and
4. `hurumap` will resemble-ish what we have in the CMS i.e. `{ profile, geography, tutorial, panels }`

**Review by kilemensi — APPROVED** [review]
Code LGTM!

**Review by koechkevin — APPROVED** [review]

File: apps/climatemappedafrica/src/lib/data/blockify/index.js (hunk 3 above)
Comment (kilemensi) [reply apps/climatemappedafrica/src/lib/data/blockify/index.js:20]: Another signature option, and probably a better one since it'll align with signature of `getPageProps` is:
```js
blockify(api, context, page, settings) {
```

File: apps/climatemappedafrica/src/components/Navigation/ExploreNavigation/index.js (hunk 2 above)
Comment (kelvinkipruto) [reply apps/climatemappedafrica/src/components/Navigation/ExploreNavigation/index.js:75]: Since we do not expect any other label update for this soon, we can leave it as is.
