### PR TITLE
FIxed Hero Mobile styles.

### LINKED ISSUE #975: Hero Mobile View
Hero doesn't match PesaYetu look in mobile

### PesaYetu
Image

### PR DESCRIPTION
**Pull request by koechkevin**
Removed useStyles in Dropdown Search

## Description

This PR fixes styling issues on Hero Component

Fixes #975 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Screenshots
image
image

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by kilemensi** [comment]
In desktop, why doesn't the hero align with the navbar? Feels like there is extra left/right margin/padding added.

File: apps/climatemappedafrica/src/components/Hero/Hero.js [hunk 1]
```diff
@@ -49,20 +49,11 @@ function Hero({
...
-              display: {
-                xs: "none",
-                md: "block",
-              },
-            }}
-            item
-            lg={1}
-          />
-          <Grid item xs={12} md={7} lg={6}>
+          <Grid sx={{ pb: { xs: 5 } }} item xs={12} md={7} lg={6}>
```
Comment (kilemensi) [inline apps/climatemappedafrica/src/components/Hero/Hero.js:56]: Put the `sx` on the `RichHeader`; it's the only component in the `Grid item`.

**Review by kilemensi — APPROVED** [review]
Haven't run it locally but code LGTM!

**Review by kelvinkipruto — APPROVED** [review]
